=== irensaltali/serverlessapigateway/worker/src/api-config.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://serverlessapigateway.com/api-config.schema.json",
    "title": "API Gateway Config",
    "description": "Configuration for the Serverless API Gateway",
    "type": "object",
    "properties": {
        "servers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "alias": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string",
                        "format": "idn-hostname"
                    }
                },
                "required": [
                    "alias",
                    "url"
                ]
            }
        },
        "cors": {
            "type": "object",
            "properties": {
                "allow_origins": {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "anyOf": [
                            {
                                "type": "string",
                                "format": "idn-hostname"
                            },
                            {
                                "const": "*"
                            }
                        ]
                    }
                },
                "allow_methods": {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "enum": ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH", "*"]
                    }
                },
                "allow_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expose_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "allow_credentials": {
                    "type": "boolean"
                },
                "max_age": {
                    "type": "integer"
                }
            },
            "required": [
                "allow_origins",
                "allow_methods",
                "allow_headers",
                "expose_headers",
                "allow_credentials",
                "max_age"
            ]
        },
        "authorizer": {
            "type": "object",
            "properties": {
                "type": {
                    "const": "jwt"
                },
                "secret": {
                    "type": "string"
                },
                "algorithm": {
                    "const": "HS256"
                },
                "audience": {
                    "type": "string"
                },
                "issuer": {
                    "type": "string"
                }
            },
            "required": [
                "type",
                "secret",
                "algorithm",
                "issuer"
            ]
        },
        "paths": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "method": {
                        "enum": ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH", "ANY"]
                    },
                    "path": {
                        "type": "string",
                        "format": "pathStart"
                    },
                    "integration": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "enum": ["http", "http_proxy"]
                            },
                            "server": {
                                "type": "string",
                                "$ref": "#/properties/servers/items/properties/alias"
                            }
                        },
                        "required": [
                            "type",
                            "server"
                        ]
                    },
                    "auth": {
                        "type": [
                            "boolean",
                            "null"
                        ]
                    },
                    "mapping": {
                        "type": "object",
                        "properties": {
                            "headers": {
                                "type": "object"
                            },
                            "query": {
                                "type": "object"
                            }
                        }
                    },
                    "variables": {
                        "type": "object"
                    },
                    "response": {
                        "type": [
                            "object",
                            "string"
                        ],
                        "properties": {
                            "status": {
                                "type": "string"
                            }
                        }
                    }
                },
                "required": [
                    "method",
                    "path"
                ]
            }
        },
        "variables": {
            "type": "object"
        }
    },
    "required": [
        "paths"
    ]
}

=== irensaltali/serverlessapigateway/worker/src/api-config.json
{
    "servers": [
        {
            "alias": "ngrok",
            "url": "https://a8ee-176-88-98-23.ngrok-free.app"
        }
    ],
    "cors": {
        "allow_origins": ["*"],
        "allow_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        "allow_headers": ["*"],
        "expose_headers": ["*"],
        "allow_credentials": true,
        "max_age": 3600
    },
    "authorizer": {
        "type": "jwt",
        "secret": "TESTcc7e0d44fd473002f1c42167459001140ec6389b7353f8088f4d9a95f2f596f2",
        "algorithm": "HS256",
        "audience": "opensourcecommunity",
        "issuer": "serverlessapigw"
    },
    "paths": [
        {
            "method": "GET",
            "path": "/api/v1/mapping",
            "integration": {
                "type": "http_proxy",
                "server": "ngrok"
            },
            "auth": true,
            "mapping": {
                "headers": {
                    "key": "$request.header.key",
                    "key2": "$request.jwt.key2",
                    "key3": "$config.key3",
                    "key4": "$request.query.key4"
                },
                "query": {
                    "key": "$request.query.key",
                    "key2": "$request.jwt.key2",
                    "key3": "$config.key3",
                    "key4": "$request.query.key4"
                }
            },
            "variables": {
                "key3": "value3"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/auth",
            "response": {
                "status": "this is authenticated GET method"
            },
            "auth": true
        },
        {
            "method": "GET",
            "path": "/api/v1/no-auth",
            "response": {
                "status": "this is un-authenticated GET method"
            },
            "auth": false
        },
        {
            "method": "GET",
            "path": "/api/v1/ngrok",
            "integration": {
                "type": "http_proxy",
                "server": "ngrok"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/ngrok/{parameter}",
            "integration": {
                "type": "http_proxy",
                "server": "ngrok"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/ngrok/proxy/{.+}",
            "integration": {
                "type": "http_proxy",
                "server": "ngrok"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/method",
            "response": {
                "status": "this is GET method"
            }
        },
        {
            "method": "POST",
            "path": "/api/v1/method",
            "response": {
                "status": "this is POST method"
            }
        },
        {
            "method": "ANY",
            "path": "/api/v1/method",
            "response": {
                "status": "this is ANY method"
            }
        },
        {
            "method": "OPTIONS",
            "path": "/api/v1/method",
            "response": {
                "status": "this is OPTIONS method"
            }
        },
        {
            "method": "POST",
            "path": "/api/v1/ngrok",
            "integration": {
                "type": "http_proxy",
                "server": "ngrok"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/health",
            "response": {
                "status": "ok"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/health/ready",
            "response": {
                "status": "ready ok"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/health/live",
            "response": {
                "status": "live ok"
            }
        },
        {
            "method": "GET",
            "path": "/api/v1/health/string",
            "response": "string ok"
        },
        {
            "method": "POST",
            "path": "/api/v1/health",
            "response": {
                "status": "ok"
            }
        }
    ]
}
